---
- hosts: all
  handlers:
    - name: reinicia o apache
      service: 
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'apt-get Atualiza o repositório e o cache'
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: yes

    - name: "Instala pacotes de dependencias do SO"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php7.4
        - apache2
        - libapache2-mod-php7.4
        - php7.4-gd
        - libssh-4
        - mysql-server-8.0
        - php7.4-mysql
        -
    - name: "Instala o Python3"
      apt:
        name: python3-pip
        state: present
      become: yes

    - name: "Instala o PyMySQL"
      pip:
        name: PyMySQL
      become: yes
 
    - name: 'Cria o banco de dados mysql - wordpress_db'
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: wordpress_db
        state: present 
      become: yes

    - name: 'Cria usuário do MySQL'
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: wordpress_user
        password: teste
        priv: 'wordpress_db.*:ALL'
        state: present
      become: yes
 
    - name: 'Download do Wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'

    - name: 'Descompacta o wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: True
      become: yes

    - name: 'Copia o arquivo de configuração de exemplo para a pasta desejada'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes
    
    - name: 'Configura o wp-config com as entradas do banco de dados'     
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
          - { regex: 'database_name_here', value: 'wordpress_db'}
          - { regex: 'username_here', value: 'wordpress_user'}
          - { regex: 'password_here', value: 'teste'}
      become: yes

    - name: 'Configura o 000-default.conf com o caminho correto'     
      replace:
        path: '/etc/apache2/sites-available/000-default.conf'
        regexp: '/var/www/html'
        replace: '/var/www/wordpress'
      become: yes
      notify:
        - reinicia o apache