---
- hosts: all
  tasks:
    - name: 'apt-get Atualiza o repositório e o cache'
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: yes
  
- hosts: database
  roles:
    - mysql

- hosts: wordpress
  roles:
    - webservice
    - wordpress    
